&ACCESS RVO
&REL 161
&COMMENT Ansteuerung Micromaster Frequenzumrichter
&PARAM EDITMASK = *
&PARAM TEMPLATE = C:\KRC\Roboter\Template\ExpertSubmit
DEF HmiSps( )

;************************************************
;              CNC Robotics Ltd
;              www.cncrobotics.co.uk
;************************************************
;     Contact: helpdesk@cncrobotics.co.uk
;     Date: 12/09/23
;     Version: 0.14.48
;************************************************
; Description: sps to HMI features.
;              Defines the state of the cell and calls
;              the high priority interrupts
;************************************************
LOOP
	AutoChangeToolHmi()
	CeadHmi()
	RobotHmi()
   EOAChangerHmi()
   FlexxPumpHmi()
   RoofHmi()
	ToolRackHmi()
	ToolMeasureHmi()
	CowlHmi()
	ChillerHmi()

	;IF $PRO_STATE1 == #P_FREE THEN
	;   strCurrentProgName[] = "No Program"
	;ELSE
	;  IF NOT(strComp( $PRO_NAME1[],strCurrentProgName[],#NOT_CASE_SENS)) THEN 
	;    strCurrentProgName[] = $PRO_NAME1[]
	;  ENDIF
	;ENDIF
	
	
ENDLOOP
END